/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./../src/components/layout/Footer/index.vue')['default']
    Header: typeof import('./../src/components/layout/Header/index.vue')['default']
    NavMenu: typeof import('./../src/components/basic/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/components/layout/Sidebar/index.vue')['default']
  }
}
